spring:
  application:
    name: coralcobragames

  datasource:
    url: jdbc:postgresql://localhost:5432/coralcobra_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # use "validate" ou "none" em produção
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect